name: Upload APK to Appetize.io

on:
  push:
    paths:
      - 'assets/Minecraft_1.21.60.10.apk'

jobs:
  upload_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Upload APK to Appetize.io (using API)
        id: upload_apk
        run: |
          # Replace with your Appetize.io API token and file URL
          response=$(curl --http1.1 https://api.appetize.io/v1/apps \
            -H 'Authorization: Bearer tok_pq2qemvv42jasn3bet637ewgsa' \
            -H 'Content-Type: application/json' \
            -d '{"url": "https://pokemogukunns.github.io/assets/Minecraft_1.21.60.10.apk", "platform": "android"}')
          
          # Extract emulator link from the response
          emulator_link=$(echo $response | jq -r '.url')
          echo "EMULATOR_LINK=$emulator_link" >> $GITHUB_ENV

      - name: Output emulator link
        run: echo "Appetize.io Emulator Link:${{ env.EMULATOR_LINK }}"

      - name: Verify current index.html content
        run: |
          echo "Current index.html content:"
          cat index.html

      - name: Update index.html with emulator link
        run: |
          echo "Updating index.html with the emulator link"
          sed -i '' "s|YOUR_GENERATED_EMULATOR_LINK|${{ env.EMULATOR_LINK }}|g" index.html

      - name: Verify updated index.html content
        run: |
          echo "Updated index.html content:"
          cat index.html
          
      - name: Commit and push changes to GitHub
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your GitHub Username"
          git add index.html
          git commit -m "Update index.html with new emulator link"
          git push
